version: "3"
services:
    penin:
        image: "penin:dev"
        build:
            context: .
            dockerfile: Dockerfile
        hostname: penin
        stdin_open: true
        tty: true
        working_dir: '/penin-dev'
        volumes:
            - ".:/penin-dev"
